name: popeye
version: '0.1.0.0'
synopsis: Generate an authorized_keys file from an IAM group
description: Please see README.md
category: Network
author: Pat Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2017 Code Climate
license: MIT
github: codeclimate/popeye
homepage: http://github.com/codeclimate/popeye#readme

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
  - amazonka
  - amazonka-iam
  - lens
  - optparse-applicative
  - text
  - transformers

executables:
  popeye:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - popeye

    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -static
        - -optl-static
        - -optl-pthread
      else:
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N

tests:
  popeye-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - popeye
    - hspec
    - QuickCheck

flags:
  static:
    description: Compile statically
    manual: false
    default: false
